### ISSUE TITLE
add option to enable/disable luaformat

### ISSUE THREAD

**Issue by caizongchao** [yinfei8/LuaHelper#1]
Is it possible to add an option to enable/disable luaformat? For now I have to edit the source file to disable the format provider.

Thanks for the extension and I found it very useful.

**Comment by yinfei8** [comment]
Thank you for using.
Will you format the file when you save it? 
VSCode has configuration control whether to save file for formatting.

![image](https://user-images.githubusercontent.com/4758080/84719421-eedec000-afad-11ea-9fc5-40e49f5ad16c.png)

Editor:Format On Save set no

**Comment by caizongchao** [comment]
ok, thanks for the solution.
