### ISSUE TITLE
hover提示乱码

### ISSUE THREAD

**Issue by LightenPan** [yinfei8/LuaHelper#12]
文件是gb2312编码时，函数的hover提示乱码，utf8文件编码则正常。

vscode-lua插件没这个问题

![image](https://user-images.githubusercontent.com/1561240/101339849-e65ea680-38b9-11eb-9def-919aa7d15b82.png)

**Comment by yinfei8** [comment]
你好，多谢反馈，这个我用gb2312编码的文件测试细

**Comment by yinfei8** [comment]
> 文件是gb2312编码时，函数的hover提示乱码，utf8文件编码则正常。
> 
> vscode-lua插件没这个问题
> 
> ![image](https://user-images.githubusercontent.com/1561240/101339849-e65ea680-38b9-11eb-9def-919aa7d15b82.png)

最新的0.1.41版本已经修复了上面的问题

**Comment by LightenPan** [comment]
感谢，已修复。
