### ISSUE TITLE
format文件必报错

### ISSUE THREAD

**Issue by Homurua** [yinfei8/LuaHelper#14]
![图片](https://user-images.githubusercontent.com/8419862/101854493-9d01a600-3b9c-11eb-9dff-28baa73f914e.png)

版本	Windows 10 专业版
版本号	20H2

插件版本：商店最新，v0.1.41

任何一个lua文件格式化就会报这个错误

**Comment by Homurua** [comment]
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by yinfei8** [comment]
> Version: 1.51.1 (user setup)
> Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
> Date: 2020-11-10T23:34:32.027Z
> Electron: 9.3.3
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows_NT x64 10.0.19042

上面的问题，之前没有遇到多，具体也怎么好定位，能否加一个QQ帮忙定位下？
QQ：313745207

**Comment by Homurua** [comment]
感谢大佬，突然正常了
