### ISSUE TITLE
LUA Format not working

### ISSUE THREAD

**Issue by Walkerbo** [yinfei8/LuaHelper#2]
I have Lua Helper installed.
When I try to format my code I get the following pop up 
<img width="355" alt="Annotation 2020-07-31 170222" src="https://user-images.githubusercontent.com/35990554/89009416-d7864700-d34f-11ea-90b2-38b677ce5522.png">
I hope this can be fixed.

**Comment by yinfei8** [comment]
Thanks for using our plugin, you did not actively open a lua project folder。We will repair it and it will take about 1 month.

**Comment by yinfei8** [comment]
> I have Lua Helper installed.
> When I try to format my code I get the following pop up
> <img alt="Annotation 2020-07-31 170222" width="355" src="https://user-images.githubusercontent.com/35990554/89009416-d7864700-d34f-11ea-90b2-38b677ce5522.png">
> I hope this can be fixed.

We have solved this problem in the latest version(0.1.21), thank you for your feedback.
