### ISSUE TITLE
for 循环没有注释提示

### ISSUE THREAD

**Issue by kaishiqi** [yinfei8/LuaHelper#20]
```lua
---@class Cat
local Cat = class()

function Cat:test()
end


---@type table<string, Cat>
local catsMap = {}


---@return table<string, Cat>
function getCatsMap()
    return catsMap
end


---@param catData Cat
for catId, catData in pairs(getCatsMap()) do
    catData:test()  -- 这句打的时候没提示
end
```

如题，这是一个简单的例子，for循环中的提示还是蛮常用的，期待这个支持能早日向emmet一样。
这是我在vscod中用到的最好用的插件了，所以很期待能早日解决这个需求，感激不尽~谢谢辛苦付出的作者

**Comment by yinfei8** [comment]
恩，好的，多谢反馈，这个例子我们会尽快验证并解决

**Comment by yinfei8** [comment]
非常感谢你的反馈
目前最新的0.1.50版本已经修复了上面的bug

注解有很强的推导跟踪功能，你上面的例子可以最简化如下面的：
`---@class Cat
local Cat = class()

function Cat:test()
end

---@type table<string, Cat>
local catsMap = {}


function getCatsMap()
    return catsMap
end

for catId, catData in pairs(getCatsMap()) do
    
end`
![image](https://user-images.githubusercontent.com/4758080/114029056-b943f400-98ab-11eb-8364-f276a2556fcb.png)

**Comment by kaishiqi** [comment]
亲测已修！感谢作者的辛勤，又可以愉快的coding了
