### ISSUE TITLE
如何自定义luaformatter?在项目根目录放置了.lua-format文件不起作用

### ISSUE THREAD

**Issue by xiangnanscu** [yinfei8/LuaHelper#3]
默认indent是4个空格, 但是我希望是2个空格.
```
indent_width: 2
```
我阅读了LuaFormatter的文档, 在项目根目录放置了`.lua-format`文件不起作用.已经重启了vs code

**Comment by yinfei8** [comment]
目前LoaFormatter的格式控制，只在插件目录里面
后面这个会优化
![image](https://user-images.githubusercontent.com/4758080/89151840-6daaaf00-d594-11ea-8b7e-c0a1633f83ff.png)

**Comment by xiangnanscu** [comment]
thanks. by the way, if in wsl, the location is `~/.vscode-server/extensions/yinfei.luahelper-0.1.14/server/luafmt.config`
