### ISSUE TITLE
err vscodeRoot: is not exist

### ISSUE THREAD

**Issue by boris-gu** [yinfei8/LuaHelper#4]
How to reproduce the bug
Method 1:

1. open a new vscode window (CTRL+SHIFT+O)
2. CTRL + O
3. Select the .lua file

Method 2:

1. Open Windows File Explorer
2. Open the .lua file with a double click

![image](https://user-images.githubusercontent.com/44787162/89794537-dca57c00-db2f-11ea-8e99-de2c2c2b0ef7.png)

**Comment by yinfei8** [comment]
Thanks for using our plugin, you did not actively open a lua project folder。We will repair it and it will take about 1 month.

**Comment by shellbombs** [comment]
+1

**Comment by yinfei8** [comment]
We have solved this problem in the latest version(0.1.21), thank you for your feedback.

**Comment by yinfei8** [comment]
> +1

We have solved this problem in the latest version(0.1.21), thank you for your feedback.

**Comment by yinfei8** [comment]
> How to reproduce the bug
> Method 1:
> 
> 1. open a new vscode window (CTRL+SHIFT+O)
> 2. CTRL + O
> 3. Select the .lua file
> 
> Method 2:
> 
> 1. Open Windows File Explorer
> 2. Open the .lua file with a double click
> 
> ![image](https://user-images.githubusercontent.com/44787162/89794537-dca57c00-db2f-11ea-8e99-de2c2c2b0ef7.png)

We have solved this problem in the latest version(0.1.21), thank you for your feedback.
