### ISSUE TITLE
Warn Type 15 is wrong

### ISSUE THREAD

**Issue by Nalleyer** [yinfei8/LuaHelper#5]
``` lua
local a = {
    b = 3
}
local c = (a and a.b) or true
print(c)
```

when you run this code, you got 3. but lua helper says:

```
[Warn type:15], or expression is always true [4, 12]
```

**Comment by yinfei8** [comment]
var c is always true

The following example：
local a = b or true
we think a is always true，maybe some thing wrong

**Comment by yinfei8** [comment]
If you want to ignore this kind of warning, you can cancel it.
![image](https://user-images.githubusercontent.com/4758080/92990216-1beb3200-f50d-11ea-9827-3cb5c151e25b.png)
