### ISSUE TITLE
Option to disable lint

### ISSUE THREAD

**Issue by nodgear** [yinfei8/LuaHelper#7]
Using the extension to deal with GLua, which is a LUA api for GMOD.
The lint constantly shows errors about GLua syntax implementations (! instead of not) (|| instead of or).

Would be nice to have an option to completly disable warns on linting.

**Comment by yinfei8** [comment]
If you want to ignore this kind of warning, you can cancel it.
![image](https://user-images.githubusercontent.com/4758080/92990274-96b44d00-f50d-11ea-8db3-1ae88d881006.png)

**Comment by nodgear** [comment]
Yes, i kinda figured out and  disabled on json settings.
